#!/usr/bin/env bash
update_lsb_release() {
    sed -i /etc/lsb-release \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=Linxira|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION="Linxira OS"|'
}
update_os_release() {
    local os_release="/etc/os-release"
    sed -i "$os_release" \
        -e 's|^NAME=.*$|NAME="Linxira OS"|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME="Linxira OS"|' \
        -e 's|^ID=.*$|ID=arch|' \
        -e 's|^ID_LIKE=.*$|ID_LIKE=arch|' \
        -e 's|^ANSI_COLOR=.*$|ANSI_COLOR="38;2;0;150;199"|' \
        -e 's|^HOME_URL=.*$|HOME_URL="https://linxira.org"|' \
        -e 's|^DOCUMENTATION_URL=.*$|DOCUMENTATION_URL="https://wiki.linxira.org"|' \
        -e 's|^SUPPORT_URL=.*$|SUPPORT_URL="https://github.com/Linxira-OS"|' \
        -e 's|^BUG_REPORT_URL=.*$|BUG_REPORT_URL="https://github.com/Linxira-OS/linxira-iso/issues"|' \
        -e 's|^LOGO=.*$|LOGO=linxira|'
    if ! grep -q "^ID_LIKE=" "$os_release" && grep -q "^ID=" "$os_release"; then
        sed -i "$os_release" -e '/^ID=/a \ID_LIKE=arch'
    fi
}
update_issues() {
    sed -i 's|CachyOS|Linxira OS|g' /etc/issue /usr/share/factory/etc/issue 2>/dev/null || true
    sed -i 's|cachyos|linxira|g' /etc/issue /usr/share/factory/etc/issue 2>/dev/null || true
}
case "$1" in
    os-release) update_os_release ;;
    lsb-release) update_lsb_release ;;
    *) update_os_release; update_lsb_release; update_issues ;;
esac
